### ISSUE TITLE
secure_mode is actually commented

### ISSUE THREAD

**Issue by cher-nov** [OpenGM8/GM8Emulator#20]
https://github.com/OpenGM8/GM8Emulator/blob/6c2668911c5825711b429828f4d1c8a7078a8f61/src/gml/runtime.rs#L1199

It actually is. See _The GameMaker Language (GML)_ / _Files, registry, and executing programs_ / _Executing programs_.

**Comment by notviri** [comment]
I wrote that comment on a whim but I can see where the confusion came from, in the index it's referenced in *Device specific commands* as well while the real info is in the page you mentioned. I have removed the TODO.
