### ISSUE TITLE
Actual meaning of missing -6 value in the list of 'constant-ish' GM keywords

### ISSUE THREAD

**Issue by cher-nov** [OpenGM8/GM8Emulator#21]
https://github.com/OpenGM8/GM8Emulator/blob/1fa405b1615f91b4a24c28c88a711fb120bd771a/src/gml.rs#L19-L24
https://github.com/OpenGM8/GM8Emulator/blob/e140cb67cebbee08286fc4b008a8f5fe8e84898e/src/types.rs#L9-L14

Maybe you'll be interested in the real meaning of missing `-6`: it's so-called "unspecified scope".
https://docs.yoyogames.com/source/dadiospice/002_reference/debugging/runner%20errors.html.
AFAIK, it's used only for some error messages in pre-Studio versions of GM.

**Comment by Adamcake** [comment]
Yes, -6 is not a special value in the GameMaker 8 runner. Dereferencing -6 will lead to an error in the exact same way as any other non-special negative number. It's interesting that they documented it as "Not Specified" in Studio - maybe it was previously used for a feature which doesn't exist anymore?

Anyway, I've added a comment clarifying the absence of -6. Thanks for your input.

**Comment by cher-nov** [comment]
> It's interesting that they documented it as "Not Specified" in Studio - maybe it was previously used for a feature which doesn't exist anymore?

It's really doubtful, since I had examined all the classic versions of GM while searched for undocumented features, and didn't find any remarks regarding this. But, as I've already stated, I can definitely recall that I saw sometime an error message with "unspecified scope" mentioned, so I believe that this is just an internal implementation detail, somewhat like fallback value, just like these weird `<undefined>` strings returned from some functions.

**Comment by Adamcake** [comment]
So an interesting thing I just discovered: dereferencing while -6 doesn't have a special name, it actually works the same as self, so (-6).x is the same as self.x, while all values below -7 produce an error. This is reflected in 9a946da and for now I've named -6 "SELF2".
