### ISSUE TITLE
Implement string multiplication operator

### ISSUE THREAD

**Issue by cher-nov** [OpenGM8/GM8Emulator#22]
Classic GM actually has it. Example:

`text = "foo" + 3 * "bar";`

After that, the `text` variable will contain a `"foobarbarbar"` string value.
Note that this operation is not commutative, i.e.

`text = "bar" * 3;`

is illegal and will lead to a syntax error.

**Comment by notviri** [comment]
I remember trying this earlier, that's really stupid... `3 * "bar"` is valid but `"bar" * 3` is invalid. Seems like a massive oversight on their part, thanks.

**Comment by Adamcake** [comment]
I wonder if there are any other string-real binary operations that we've missed?

**Comment by cher-nov** [comment]
https://github.com/OpenGM8/GM8Emulator/blob/05434617ed8173d9c82fa8fd9464bba2e4c43442/src/gml/value.rs#L258-L259

@notviri, why do you rounding here `lhs` two times, each with a different method? (`ieee_round()` for `repeat` variable and `.round()` for the method argument`)?

**Comment by notviri** [comment]
because it's really late, and I'm dumb
