### ISSUE TITLE
Emulating buggy behavior of modify-then-assign operators

### ISSUE THREAD

**Issue by cher-nov** [OpenGM8/GM8Emulator#23]
Operators like `+=` were implemented in GM in a pretty clunky way - through unfolding them to their full forms. For example, `x += 1` would become `x = x + 1`.

This gave rise to a very funny bug.
As you know, GM also has the syntax to modify a variable in all instances at the moment:

```gml
object0.speed = 0;
```

But attempt to access the `object0.speed`, however, will result in a value of `speed` variable from the 1st instance of `object0`.

So, when you'll try to use both this syntax and a modify-then-assign operator, e.g.

```gml
object0.speed += 0.5;
```

the expression will be transformed to

```gml
object0.speed = object0.speed + 0.5;
```

which is literally "assign the `speed` variable of every `object0` instance to the value of `speed`, increased by 0.5, from the 1st `object0` instance".

Since the goal of your project is to "mimic the behaviour of GameMaker 8's engine as closely as possible", this should be implemented, I believe. Even while being really ugly, yes.

An example project is there: [gm_bug_test.zip](https://github.com/OpenGM8/GM8Emulator/files/4574528/gm_bug_test.zip)

**Comment by Adamcake** [comment]
Fixed in b4f0999. The compiler now expands these out into assignment instructions. I suppose the ModifyField/ModifyVariable instructions are redundant now since it seems they don't really exist in GameMaker.
